version: '3'
services:
  db:
    build: ./dockerfiles/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
    ports:
      - "3306:3306"
  web:
    build: ./dockerfiles/glassfish
    ports:
      - "8081:8080"
      - "4849:4848"
      - "8182:8181"
  prom:
      build: ./dockerfiles/prometheus
      ports:
        - "9090:9090"
  grafana:
      image: grafana/grafana
      ports:
        - "3000:3000" 