
package com.freimanvs.company.soapjaxws.bank.fromwsdl;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TaxCalculatorService", targetNamespace = "http://bank.soapjaxws.company.freimanvs.com/", wsdlLocation = "http://localhost:8080/company/TaxCalculatorService?wsdl")
public class TaxCalculatorService
    extends Service
{

    private final static URL TAXCALCULATORSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.freimanvs.company.soapjaxws.bank.fromwsdl.TaxCalculatorService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.freimanvs.company.soapjaxws.bank.fromwsdl.TaxCalculatorService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/company/TaxCalculatorService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/company/TaxCalculatorService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TAXCALCULATORSERVICE_WSDL_LOCATION = url;
    }

    public TaxCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaxCalculatorService(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://bank.soapjaxws.company.freimanvs.com/", "TaxCalculatorService"));
    }

    public TaxCalculatorService() {
        super(TAXCALCULATORSERVICE_WSDL_LOCATION, new QName("http://bank.soapjaxws.company.freimanvs.com/", "TaxCalculatorService"));
    }

    /**
     * 
     * @return
     *     returns TaxCalculator
     */
    @WebEndpoint(name = "TaxCalculatorPort")
    public TaxCalculator getTaxCalculatorPort() {
        return super.getPort(new QName("http://bank.soapjaxws.company.freimanvs.com/", "TaxCalculatorPort"), TaxCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaxCalculator
     */
    @WebEndpoint(name = "TaxCalculatorPort")
    public TaxCalculator getTaxCalculatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bank.soapjaxws.company.freimanvs.com/", "TaxCalculatorPort"), TaxCalculator.class, features);
    }

}
