
package com.freimanvs.company.soapjaxws.bank.fromwsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TaxCalculator", targetNamespace = "http://bank.soapjaxws.company.freimanvs.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TaxCalculator {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exec", targetNamespace = "http://bank.soapjaxws.company.freimanvs.com/", className = "com.freimanvs.company.soapjaxws.bank.fromwsdl.Exec")
    @ResponseWrapper(localName = "execResponse", targetNamespace = "http://bank.soapjaxws.company.freimanvs.com/", className = "com.freimanvs.company.soapjaxws.bank.fromwsdl.ExecResponse")
    public double exec(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
